name: Deploy Hugo site to Pages

# トリガー
"on":
  push:
    branches:
      - main
  workflow_dispatch:

# GitHub Pagesに更新するためのGITHUB_TOKEN権限
permissions:
  contents: read
  pages: write
  id-token: write

# 同時デプロイ防止してスキップする。
# ただし実行中デプロイはキャンセルしない。
concurrency:
  group: pages
  cancel-in-progress: false

# Github Runnerのシェル
defaults:
  run:
    shell: bash

jobs:
  build:
    # ジョブに必要な定義
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.125.4

    steps:
      # ブランチの内容をチェックアウト（ダウンロード）する
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # no_discord.txtがあるか確認。
      - name: Check file notification
        id: no_discord
        uses: andstor/file-existence-action@v3
        with:
          files: ./no_discord.txt

      # 記事にAuthorタグがついているかチェックする。
      - name: Front Matter check
        run: |
          er_cnt=0
          for file in $(find ./content/ -name '*.md' | sed -ne "/_index.md/d"); do
            tag_author=$(cat $file | sed -ne "/tags \= \[/p" | sed -ne "/Author:/p")
            if [ -z "$tag_author" ]; then
              echo "::error:: No Tag \"Author\": $file"
              er_cnt=$(expr $er_cnt + 1)
            fi
          done
          if [ $er_cnt -eq 0 ]; then exit 0; else exit 1; fi
