name: Deploy Hugo site to Pages

# トリガー
"on":
  push:
    branches:
      - main
  workflow_dispatch:

# GitHub Pagesに更新するためのGITHUB_TOKEN権限
permissions:
  contents: read
  pages: write
  id-token: write

# 同時デプロイ防止してスキップする。
# ただし実行中デプロイはキャンセルしない。
concurrency:
  group: pages
  cancel-in-progress: false

# Github Runnerのシェル
defaults:
  run:
    shell: bash

jobs:
  build:
    # ジョブに必要な定義
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.125.4

    steps:
      # ブランチの内容をチェックアウト（ダウンロード）する
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # no_discord.txtがあるか確認。
      - name: Check file notification
        id: no_discord
        uses: andstor/file-existence-action@v3
        with:
          files: ./no_discord.txt

      # 記事にAuthorタグがついているかチェックする。
      - name: Post author tag check
        continue-on-error: true
        run: |
          for file in $(find ./content/ -name '*.md' | grep -vE _index.md); do
            check=$(cat $file | sed -n -E -e "tags \= \[" | sed -n -E -e "Autor:")
            echo "$file : $check"
            notagfile+=("$file")
          done
          echo "notagfile=$notagfile" >> $GITHUB_ENV

      # Authorタグがついていない記事が存在していたらエラーにする。
      - name: ERROR Action
        if: env.notagfile != null
        run: |
          echo "::error:: ${{ env.notagfile }}"
          exit 1
