name: SYNC-FROM-PROD

on:
  # Github Actionsのタブから手動実行
  workflow_dispatch:

# Github Runnerのシェル
defaults:
  run:
    shell: bash

jobs:
  # ジョブ
  directory-changes:
    # ジョブに必要な定義
    name: sync
    runs-on: ubuntu-latest

    steps:
      # staging側リポジトリをclone
      - name: Clone from staging
        uses: actions/checkout@v4.1.4
        with:
          path: staging

      # prod側リポジトリをclone
      - name: Clone from masaru-study/verify-note (prod)
        uses: actions/checkout@v4.1.4
        with:
          repository: masaru-study/verify-note
          path: prod

      # 現在時刻を変数に格納
      - name: Get Timestamp
        id: timestamp
        run: echo "value=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      # prod側をstaging側に反映。一部除外
      # .git
      # workflows
      - name: Restore files
        run: |
          rsync -av --delete --exclude .git --exclude workflows "./prod/" "./staging/"
          pushd "./staging/.github" && unlink "./README.md" &&  ln -s "./src-readme/README-staging.md" "./README.md" && popd

      #プルリク作成
      - name: Create Pull Request
        uses: Peter-evans/create-pull-request@v6.0.5
        with:
          commit-message: "Sync from prod ${{ steps.timestamp.outputs.value }}"
          branch: sync/actions-${{ steps.timestamp.outputs.value }}
          base: main
          path: ./staging

      # 作成したプルリクをマージ
      - name: Auto Merge
        run: gh pr merge --merge --auto sync/actions-${{ steps.timestamp.outputs.value }}
        env:
          GH_TOKEN: ${{ github.token }}
