name: SYNC-FROM-PROD

on:
  # Github Actionsのタブから手動実行
  workflow_dispatch:

# Github Runnerのシェル
defaults:
  run:
    shell: bash

jobs:
  # ジョブ
  directory-changes:
    # ジョブに必要な定義
    name: sync
    runs-on: ubuntu-latest

    steps:
      # staging側リポジトリをclone
      - name: Clone from staging
        uses: actions/checkout@v4.1.4

      # prod側リポジトリをclone
      - name: Clone from masaru-study/verify-note (prod)
        uses: actions/checkout@v4.1.4
        with:
          repository: masaru-study/verify-note
          path: prod-verify-note

      # 現在時刻を変数に格納
      - name: Get Timestamp
        id: timestamp
        run: echo "value=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      # staging側リポジトリの一部ファイルを復元
      # .github/worlflow/
      # .github/README.md
      - name: Restore files
        run: |
          rsync -av --delete --exclude="./.git" --exclude="./.github/workflows" "./prod-verify-note" "./" 
          unlink "./.github/README.md" && pushd "./.github" && ln -s "./src-readme/README-staging.md" "./README.md" && popd

      # cloneしたprod側のファイルを削除
      - name: Clean files
        run: rm -rf "./prod-verify-note"

      # プルリク作成
      - name: Create Pull Request
        uses: Peter-evans/create-pull-request@v6.0.5
        with:
          commit-message: "Update Assets"
          branch: sync/actions
          branch-suffix: ${{ steps.timestamp.outputs.value }}
          base: main
