name: SYNC-FROM-PROD

on:
  # Github Actionsのタブから手動実行
  workflow_dispatch:

# Github Runnerのシェル
defaults:
  run:
    shell: bash

jobs:
  # ジョブ
  directory-changes:
    # ジョブに必要な定義
    name: sync
    runs-on: ubuntu-latest

    steps:
      # test側リポジトリをclone
      - name: Clone from test
        uses: actions/checkout@v4.1.4
        with:
          path: test

      # prod側リポジトリをclone
      - name: Clone from masaru-study/verify-note (prod)
        uses: actions/checkout@v4.1.4
        with:
          repository: masaru-study/verify-note
          path: prod

      # 現在時刻を変数に格納
      - name: Get Timestamp
        id: timestamp
        run: echo "value=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      # prod側をtest側に反映。一部除外(.git workflows)
      # workflowsを別フォルダでコピー
      # READMEをtest用に切り替える。
      - name: Restore files
        run: |
          rsync -av --delete --exclude .git --exclude workflows "./prod/" "./test/"
          cp -r ./prod/.github/workflows ./test/.github/prod-workflows
          pushd "./test/.github" && unlink "./README.md" &&  ln -s "./src-readme/README-test.md" "./README.md" && popd

      #プルリク作成
      - name: Create Pull Request
        uses: Peter-evans/create-pull-request@v6.0.5
        with:
          commit-message: "Sync from prod ${{ steps.timestamp.outputs.value }}"
          branch: sync/actions-${{ steps.timestamp.outputs.value }}
          base: main
          path: ./test
