name: Sync from prod

on:
  # Github Actionsのタブから手動実行
  workflow_dispatch:

# Github Runnerのシェル
defaults:
  run:
    shell: bash

jobs:
  # ジョブ
  directory-changes:
    # ジョブに必要な定義
    name: Copy Assets
    runs-on: ubuntu-latest

    steps:
      # prod側リポジトリをclone
      - name: Clone from masaru-study/verify-note (prod)
        uses: actions/checkout@v4.1.4
        with:
          repository: masaru-study/verify-note

      # staging側リポジトリをclone
      - name: Clone from staging
        uses: actions/checkout@v4.1.4
        with:
          path: staging-verify-note

      # staging側リポジトリの一部ファイルを復元
      # .github/worlflow/
      # .github/README.md
      - name: Restore files
        run: |
          rm -rf "./.github/workflows" && cp -r "./staging-verify-note/.github/workflows" "./.github/workflows"
          unlink "./.github/README.md" && cd "./.github" && ln -s "./src-readme/README-staging.md" "./README.md"

      # cloneしたprod側のファイルを削除
      - name: Clean files
        run: rm -rf "staging-verify-note"

      # プルリク作成
      - name: Create Pull Request
        uses: Peter-evans/create-pull-request@v6.0.5
        with:
          commit-message: "Update Assets"
          branch: sync/actions
          branch-suffix: timestamp
          base: main
